export enum AdminTypes {
  ADD_PREPARE = "ADD_PREPAPRE",
  REMOVE_PREPARE = "REMOVE_PREPARE",
  CHANGE_INPUTS = "CHANGE",
  CHANGE_PREPARE = "CHANGE_PREPARE",
  ADD_INGREDIENT_NAME = "ADD_INGREDIENT_NAME",
  REMOVE_INGREDIENT_NAME = "REMOVE_INGREDIENT_NAME",
  CHANGE_INGREDIENT_NAME = "CHANGE_INGREDIENT_NAME",
  INGREDIENT_VALUE = "INGREDIENT_VALUE",
  ADD_INGREDIENT = " ADD_INGREDIENT",
  REMOVE_INGREDIENT = "REMOVE_INGREDIENT",
  HAM_MENU = "HAM_MENU",
  MOBILE = "MOBILE",
  DESKTOP = "DESKTOP"
}
